### ISSUE TITLE
"caching" on directories

### ISSUE THREAD

**Issue by yarikoptic** [con/fscacher#4]
This is the most interesting/challenging part of this helper module.  

- [ ] Initial implementation could just follow initially suggested by @satra in https://github.com/con/fscacher/issues/1#issuecomment-628314384 with slight tuneups/safe guards I have added in https://gist.github.com/yarikoptic/7284b634d8ab12277a3d316a117cc0db and timings for sample usecase in https://github.com/con/fscacher/issues/1#issuecomment-629365326 
- [ ] storing an entire list of stats as a "fingerprint" allows for fast decision making (if `any` of stats change) but might be prohibitively large for many target use cases; we need to research/think about a better approach. Possible immediately thought about alternatives is/are:
   - list of digest-pairs per each directory, where for each directory we have two digests: 1 - digest of the stat for the most recently modified file/directory in that directory (to detect quickly if any immediate file/directory was modified), 2 - joint digest of all other entries in the directory.  (digest should be some fastest one to estimate on the stats records of interest)
   - but I bet we would find a better approach if we look into how git does it (I believe @kyleam and/or @mih looked into that at some point) for its `status` etc needs

<details>
<summary>thoughts which lead me to the above "list of digest-pairs"</summary>

   - store some digest of that list:
     - digest could be updated with each record -- the fastest possible (in conjunction with time it might need to take to convert stat into bytes for digest update)
     - big **cons**: no early decision making -- we would need to traverse entire tree to make a decision.  Show stopper
   - I bet there could be some hierarchical structure/tree which would allow for some not that heavy fingerprint, while allowing for early termination.  E.g. could be a digest per each directory: as soon as we run into a directory with a different digest -- early termination.  This should work but might be still not that efficient in some cases with heavy flat directories (heuristic could be to have digests per N, e.g. 100, files in a directory, so in most of the cases it would still be a single digest per directory)
   - optimization: 
     - we could sort (well -- O(N*log(N)) operation) list of files in a directory by their mtime, thus if any file is changed, mtime changed, order changed -- early detection 
     - but above shows that we do not really need to know that full order -- we just need to detect change of
       - mtime of a directory (so if file is removed or copied into while preserving its time stamps,mtime of a directory would change!)
       - digest of the most recently modified file in a directory + digest of the entire directory listing.  We would still need to do O(N) pass over all files in a directory to get the "latest", but we do not need to right away spend time on estimating the digest for the join of N items (we could multithread btw since os.stat probably would allow for some "digest"ing thread to coexist?)  So insofar I think this is the way to go
</details>

After that initial implementation we should consider following features to be added (list is likely to grow)
- [ ] add "support" for specification of paths to ignore (or consider?): #5
- [ ] add "support" for hierarchical organization.  #6

**Comment by jwodder** [comment]
@yarikoptic So what exactly are you suggesting as the structure for directory fingerprints?  What do you mean by the "digest of the stat"?

**Comment by yarikoptic** [comment]
I will elaborate, but meanwhile please check how exactly git does it

**Comment by jwodder** [comment]
@yarikoptic According to [this file in the Git source](https://github.com/git/git/blob/master/Documentation/technical/racy-git.txt), Git caches certain fields of each file's `lstat(2)` return value and compares those fields first when determining whether a file has changed.  There are also some tricks for dealing with race conditions involving checking the mtime of the index file against the mtimes of the files in the working tree.

**Comment by yarikoptic** [comment]
oh, totally forgot about the git index, status of which might indeed be of relevance to `datalad status` thus should be also checked. Complicates future #5 but "doable" ;)
So let's (re)implement git approach .  I am yet not 100% certain if storing entire tree of stats (mtime, size) for all files is the way to go , but we could time/improve later on.  We would just need to have some efficient storage/IO for such records, and keep them loaded within the process if e.g. used within a long running python process (as opposed to individual invocations of `dandi` or `datalad` from cmdline where it would need to be reloaded.

**Comment by jwodder** [comment]
@yarikoptic So the fingerprint of a directory should be, what, exactly?  A dict mapping relative paths of files to file signatures?  What are you referring to with "efficient storage/IO for such records"?

**Comment by yarikoptic** [comment]
as for "fingerprint" I thought to have something like

```python
import hashlib
import struct
import os

def get_fingerprint(paths):
    """Return a fingerprint on a paths

    To avoid storing all of them.
    Pros: lesser impact on storage,
    Cons: no early/quick decision making, all should be considered, so might better be
    used per each directory"""
    D = hashlib.sha512()
    for path in paths:
        s = os.stat(path)
        D.update(bytearray(struct.pack("fi", s.st_mtime, s.st_size)))
    return D.hexdigest()


if __name__ == '__main__':
    import sys
    print(get_fingerprint(sys.argv[1:]))
    sys.exit(0)
```

but we could start with a dict mapping (i.e. to do not compress into a single digest) -- I guess we are yet to figure out the optimal solution (either store all and deal with more IO to reload the DB with prior results; or store condensed fingerprints -- faster IO but then cannot failed as soon as one file found changed).

**Comment by yarikoptic** [comment]
<details>
<summary>grr... note: above example seems to not work exactly right -- `touch` on a file does change its mtime but fingerprint is staying the same -- did not look into why</summary> 

```shell
(git)lena:~datalad/trash[master]git
$> stat walk.py
  File: walk.py
  Size: 2857      	Blocks: 8          IO Block: 4096   regular file
Device: 31h/49d	Inode: 38528067    Links: 1
Access: (0711/-rwx--x--x)  Uid: (47521/     yoh)   Gid: (47522/     yoh)
Access: 2020-11-16 11:40:48.668152694 -0500
Modify: 2020-11-16 11:40:48.668152694 -0500
Change: 2020-11-16 11:40:48.668152694 -0500
 Birth: 2020-05-14 22:05:32.510542561 -0400
cached/staged changes:                                                                                           
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1 37871.....................................:Mon 16 Nov 2020 11:40:59 AM EST:.
(git)lena:~datalad/trash[master]git
$> python3 walk-fp.py *
837c0dd22e391e59b05ee22e0a5d5ec36af87c97f759b4758bb17efad4f6a287e2b233818ba98267e4447bcdf51562c8af4085cbd8d6ce71b3edbfcfb44399c6
cached/staged changes:                                                                                           
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1 37872.....................................:Mon 16 Nov 2020 11:41:03 AM EST:.
(git)lena:~datalad/trash[master]git
$> touch walk.py       
cached/staged changes:                                                                                           
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1 37873.....................................:Mon 16 Nov 2020 11:41:08 AM EST:.
(git)lena:~datalad/trash[master]git
$> stat walk.py        
  File: walk.py
  Size: 2857      	Blocks: 8          IO Block: 4096   regular file
Device: 31h/49d	Inode: 38528067    Links: 1
Access: (0711/-rwx--x--x)  Uid: (47521/     yoh)   Gid: (47522/     yoh)
Access: 2020-11-16 11:41:08.604140722 -0500
Modify: 2020-11-16 11:41:08.604140722 -0500
Change: 2020-11-16 11:41:08.604140722 -0500
 Birth: 2020-05-14 22:05:32.510542561 -0400
cached/staged changes:                                                                                           
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1 37874.....................................:Mon 16 Nov 2020 11:41:11 AM EST:.
(git)lena:~datalad/trash[master]git
$> python3 walk-fp.py *
837c0dd22e391e59b05ee22e0a5d5ec36af87c97f759b4758bb17efad4f6a287e2b233818ba98267e4447bcdf51562c8af4085cbd8d6ce71b3edbfcfb44399c6

```
</details>
so needs some fixing if to be "followed"

**Comment by yarikoptic** [comment]
well, let's consider that #11 initial implementation did address this issue. any particular issue/optimization would need a separate issue
